---
title: "Do More Polling Locations in Wards Increase Turnout? An Analysis of the 2022 Toronto Municipal Election"
author: "Inessa De Angelis"
thanks: "Code and data from this analysis are available at: https://github.com/InessaDeAngelis/Toronto_Elections" 
date: "today"
date-format: "long" 
abstract: "First sentence. Second sentence. Third sentence. Fourth sentence."
format: pdf
number-sections: true
bibliography: ref.bib
---

```{r}
#| message: false
#| echo: false

#### Workspace set-up ####

## Load packages
library(tidyverse)
library(knitr)
library(here)

#read in cleaned data #
cleaned_voter_statistics <- read.csv(here::here("inputs/data/cleaned_voter_statistics.csv"))
show_col_types = FALSE

cleaned_voting_locations <- read.csv(here::here("inputs/data/cleaned_voting_locations.csv"))
show_col_types = FALSE
```

## Introduction
As mandated by the Government of Ontario, residents of the City of Toronto went to the polls on October 24, 2022 to elect a mayor, councillors, and school board trustees. Then-sitting Mayor, John Tory sought re-election, along with a number of incumbent city councillors. Coming out of the height of the Covid-19 pandemic, the 2022 election largely upheld the status quo and did not feature ambitious policy platforms. Voter turnout across the city was 29.7% - the lowest in the city’s history since amalgamation in 1997, with turnout ranging on a ward-by-ward basis from 22.1% to 38.5% (Warren, 2022; Marshall, 2023). 

Individual turnout by ward largely depended on local candidates and the accessibility of subdivisions to cast a ballot. The City of Toronto @ElectionDictionary defines a ward as “a geographical area represented by a member of Council.” Following Premier Doug Ford’s decision in the summer of 2018 to cut down the number of wards in the city to match federal and provincial riding boundaries, there are currently 25 wards in the City of Toronto (Lucas & McGregor, 2021). Subdivisions are defined by the City of Toronto [@VoterStatistics] as “.... geographical area[s within a ward] designated by the City Clerk.” Previous studies concentrating on large cities in the United States, including Atlanta revealed that having polling locations in close proximity to a voter’s home bolsters turnout and even minor changes in placement of a polling location can have significant impact on a voter’s decision to cast a ballot (Haspel & Knotts, 2005). There has been little research into the impact of polling location placement in relation to election turnout, especially in Canadian cities like Toronto and this paper will contribute to the investigation of this phenomenon. 

To examine the placement of subdivisions on voter turnout, this paper is organized into the following sections: Data, Results, Discussion, and Conclusion.  In the Data section, I discuss the nature of the spreadsheets obtained through the City of Toronto’s OpenDataToronto Library [@rOpenDataToronto] and the steps I took to clean and analyze the data. The Results section highlights trends found during the analysis process, while the Discussion section further evaluates the trends and presents insight. Lastly, the Conclusion section summarizes the main findings from this paper. 

## Data
The data utilized throughout this paper was obtained through the City of Toronto’s OpenDataToronto Library [@rOpenDataToronto]. The two different data sets used are: “Elections Voting Locations” (Data, 2022) and “Elections - Voter Statistics” (Data, 2023). Data was collected and analyzed using the statistical programming software R (R Core Team, 2022), with additional support from from `tidyverse` [@rTidyverse], `ggplot2` [@rGgplot2], `dplyr` [@rDplyr], `readr` [@rReadr], `tibble` [@rTibble], and `janitor` [@rJanitor]. A further discussion of the data collection, cleaning, and analysis process can be found later on in this paper. 

### Elections Voting Locations
This dataset, published by the City Clerk's Office [@VotingLocations] highlights all polling locations and subdivisions, on a ward-by-ward basis from the 2022 municipal election. This data was last refreshed on November 2, 2022 and captured for this paper on May 21, 2023. The polling locations account for Advance Vote, election day, and Mail In Voting. One subdivision in a ward is equivalent to one polling location, based on geography. In each ward, subdivision 97 accounts for Mail In Voting, while subdivisions 98 and 99 are designated Advance Vote locations. Voters can request a Mail In ballot, go to one of the two Advance Vote locations during the designated days, or vote at their assigned subdivision on election day (for example: ward 11, subdivision 11). 
